### ISSUE TITLE
Python module to do Object operations

### ISSUE THREAD

**Issue by subhajit-muSigma** [EMCECS/python-ecsclient#38]
Is there an equivalent Python Module to List objects in a given bucket ;
 GET
            retrieve object
            retrieve object’s metadata
            retrieve object’s ACLs

PUT, POST, DELETE method as well.

**Comment by adrianmo** [comment]
Sure, you can use AWS official client [boto3](http://boto3.readthedocs.io/en/latest/reference/services/s3.html).

**Comment by subhajit-muSigma** [comment]
Thank you so much!!! Adrian.
