### ISSUE TITLE
Create Bucket

### ISSUE THREAD

**Issue by subhajit-muSigma** [EMCECS/python-ecsclient#39]
Am getting error while using 
client.bucket.create(bucket_name='bucket-test1', replication_group='REP-ECS', namespace='namespace1')

File "<stdin>", line 1, in <module>
  File "ecs.py", line 244, in create_bucket
    status = self.client.bucket.create(bucket_name, replication_group, namespace)
  File "/ecsclient/common/provisioning/bucket.py", line 85, in create
    return self.conn.post('object/bucket', json_payload=payload)
  File "/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecs.ExecutionError: Can not construct instance of java.lang.Boolean from String value 'ess_aut_ns': only "true" or "false" recognized
 at [Source: HttpInputOverHTTP@7025d20c[c=153,s=STREAM]; line: 1, column: 2] (through reference chain: com.emc.storageos.data.datasvcmodels.bucket.ObjectBucketParam["filesystem_enabled"]) - Bad request

**Comment by subhajit-muSigma** [comment]
Got it resolved. Thank you.

**Comment by adrianmo** [comment]
@subhajit-muSigma What was causing the issue? I want to know if it's something we can fix in the library or not.

Thanks.

**Comment by subhajit-muSigma** [comment]
Library is all good. My definition of namespace was wrong. Thank you for
getting back to me Adrian. I am checking all the bucket functions. Would
let you know if any issues that I come across.

Regards,
Subhajit

On Aug 24, 2017 3:32 PM, "Adrián Moreno" <notifications@github.com> wrote:

@subhajit-muSigma <https://github.com/subhajit-musigma> What was causing
the issue? I want to know if it's something we can fix in the library or
not.

Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EMCECS/python-ecsclient/issues/39#issuecomment-324591641>,
or mute the thread

**Comment by adrianmo** [comment]
Excellent @subhajit-muSigma. Sure, feel free to open another ticket if you come across any issues.

Cheers,
Adrian
