### ISSUE TITLE
Implement bucket.set_acl function

### ISSUE THREAD

**Issue by subhajit-muSigma** [EMCECS/python-ecsclient#42]
def set_acl(self):
        raise NotImplementedError()

Do we have this function added now? Please advise.

**Comment by adrianmo** [comment]
@subhajit-muSigma It's not implemented yet. But I will prioritize it if you need it.

**Comment by subhajit-muSigma** [comment]
Yes, please.

**Comment by adrianmo** [comment]
:+1:

**Comment by subhajit-muSigma** [comment]
Hello Adrian,

Could you please update if the function is available and can be used ? Thank you.

**Comment by adrianmo** [comment]
Hi @subhajit-muSigma, I'm sorry I haven't had the cycles to work on this issue yet. I'll try to allocate some time in the next two weeks to work on this and release version 1.2.

**Comment by subhajit-muSigma** [comment]
669     def set_acl(self): 
670         raise NotImplementedError() 
Hello Adrian, any update on this feature been available and be used ?

**Comment by adrianmo** [comment]
Hi @subhajit-muSigma, I'm sorry but I haven't had time and will not have to work on it in the next weeks. 

Is this a blocker for a customer use case? If it is, we can probably raise priority of this issue and find some resources to implement it.

Thank you.

**Comment by subhajit-muSigma** [comment]
Hello Adrian,

We're asked to implement a method to set acl. In the module I found only
function to set acl at the bucket level. Please advise. It is a show
stopper at the moment.

Regards,

**Comment by adrianmo** [comment]
Hi @subhajit-muSigma, I have implemented the `bucket.set_acl` method and released a new version (1.1.9). Check the following test case to see an example of usage: https://github.com/EMCECS/python-ecsclient/blob/master/tests/functional/test_bucket.py#L139

Cheers!

**Comment by subhajit-muSigma** [comment]
This is great! Thank you Adrian. Let me check and get back to you.

Regards,

**Comment by subhajit-muSigma** [comment]
Hello Adrian,

Need another help. While we're using ecsclient is it possible to get below
data for ECS.

DNS configured with all of the nameservers.



NTP configured with one of Network time Protocol servers.

 lF followingPorts  opened for

     Docker registry: XXXX

     Lifecycle agent: XXXX

     Object: XXXX-XXXX

     ZooKeeper: XXXX

 If local Management user added



Namespace administrator added



Platform locking disabled



Root mgmt password changed




*Regards,*

**Comment by adrianmo** [comment]
Hi @subhajit-muSigma, 

you can find the API documentation here: http://doc.isilon.com/ECS/3.1/API/index.html

There, you'll be able to find what resources are available through the API and check if it can provide the information you need. Please feel free to open a different issue if you need support for a specific resource/call to be implemented on the Python client.

Regards,
-Adrian
