### ISSUE TITLE
Don't pass existing_key_expiry_time_mins if zero is passed in for expiry_time

### ISSUE THREAD

**Issue by ben-schumacher** [EMCECS/python-ecsclient#56]
Can you add a check here and not pass this property if the expiry_time passed in is zero?

https://github.com/EMCECS/python-ecsclient/blob/master/ecsclient/common/user_management/secret_key.py#L94

Thanks,
Ben

**Comment by adrianmo** [comment]
Crashes when trying create a secret key for a user that doesn't have an existing secret key with the following error:

```ecsclient.common.exceptions.ECSClientException: User functional-tests-objectuser-1518099028 has no valid secret key. Cannot accept creation request with expiry for existing key. - An error occurred in the API service: https://10.1.83.61:4443/object/user-secret-keys/functional-tests-objectuser-1518099028 500 Server Error  [first 60 chars of response] {"code":70,"retryable":false,"description":"An error occurre```

At this moment, the library sets the `expiry_time` to a default value if not provided, causing the above error. One way to fix this is managing the `expiry_time` as an optional parameter and send it to ECS only if it's provided by the user.
