### ISSUE TITLE
Feature Request: Change client.bucket.create default beaviour to inherit ADO setting of namespace

### ISSUE THREAD

**Issue by dbavro19** [EMCECS/python-ecsclient#79]
The client.bucket.create('bucket') without any arguments appears to default to setting stale_allowed to false. My expectation would be that if an ADO setting is not specified in the bucket create process it should default to using the namespace level ADO setting, not enforcing ADO Disabled.

**Comment by xiaoxin-ren** [comment]
fixed in release 1.1.12
